# Generated by Django 3.2.6 on 2021-08-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='schedule_date',
        ),
    ]
