version: '3.4'

services:
  api:
    image: api
    container_name: api
    build:
      context: api
      dockerfile: ./Dockerfile.debug
    ports:
      - "8000:8000"
      - "5678:5678"
    command: sh -c "python manage.py makemigrations && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.25
    container_name: btooltek
    environment:
      MYSQL_DATABASE: btooltek
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - 3306:3306
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci

  web:
    image: web
    container_name: web
    build:
      context: web
      dockerfile: ./Dockerfile.debug
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - "./web:/app"
      - "/app/node_modules"
    command: yarn --cwd web start
    depends_on: 
      - api