# Generated by Django 3.2.6 on 2021-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210815_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.SmallIntegerField(choices=[(0, '임원'), (1, '경영지원'), (2, '영업지원'), (3, '개발'), (4, '마케팅')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.SmallIntegerField(choices=[(0, '대표이사'), (1, '이사'), (2, '부장'), (3, '차장'), (4, '과장'), (5, '대리'), (6, '주임'), (7, '사원')]),
        ),
    ]
