# Generated by Django 3.2.6 on 2021-08-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210819_0607'),
        ('users', '0005_auto_20210819_1726'),
    ]

    operations = [
    ]
